import { Injectable } from '@angular/core';
import { WatchModel } from '../../features/home/components/watch-card/watch-card';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  public watches: WatchModel[] = [
    { id: 1, name: "Classic Silver", description: "Minimalist silver design", longDescription: "A clean and timeless watch designed for everyday elegance. The Classic Silver features a polished stainless steel case, a simple dial layout, and a comfortable strap that suits both casual and formal outfits.", price: "25$", imgUrl: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/watch-card-40-s11-202509_GEO_US_FMT_WHH?wid=508&hei=472&fmt=jpeg&qlt=90&.v=RGt6QnVpU0piVDZnRHZnWmNNbHB2OTBjZHdHYTQrK3J3cVBweW1TWmNrUHNPK21NTmFtSkpWQ3ZBMFB1WTlMTzltWDc4aXJHcmduU0dwUHg2UmFtWXoyTkNERHVqSk12b05selRrakVBT3RhdGlsQnN1VnlIL253Vk5XcC9NbEM" },
    { id: 2, name: "Ocean Blue", description: "Blue dial with leather strap", longDescription: "Inspired by ocean tones, this watch combines a deep blue dial with a soft leather strap. It delivers a calm yet premium look, ideal for daily wear and relaxed business environments.", price: "30$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh_lgcs2VurZBoEbeSnAOLqCxhp7ZH_6wG6A&s" },
    { id: 3, name: "Midnight Black", description: "Elegant all-black finish", longDescription: "The Midnight Black offers a bold, stealthy aesthetic with its full black finish. Designed for those who prefer a modern and powerful look, it pairs perfectly with dark outfits and evening wear.", price: "28$", imgUrl: "https://www.maximawatches.com/cdn/shop/files/69100CMGY.jpg?v=1739601046" },
    { id: 4, name: "Rose Gold", description: "Luxury rose gold style", longDescription: "A luxurious piece with a rose gold tone that adds warmth and sophistication. This watch stands out in formal settings and is perfect for those who appreciate refined design details.", price: "45$", imgUrl: "https://www.fossil.com/on/demandware.static/-/Library-Sites-FossilSharedLibrary/default/dw294e3664/2025/HO25/set_10272025_global_holiday_lp/watches/Watches_LP_carousel_Style_Mens_classic.jpg" },
    { id: 5, name: "Sport Pro", description: "Durable sporty design", longDescription: "Built for performance and durability, the Sport Pro features a rugged design, strong materials, and a comfortable fit. Ideal for active users and outdoor activities.", price: "35$", imgUrl: "https://m.media-amazon.com/images/I/61LQq1+UVoL._AC_UY350_.jpg" },
    { id: 6, name: "Digital X", description: "Modern digital interface", longDescription: "A modern digital watch with a clean interface and practical features. Lightweight and easy to use, it's perfect for everyday functionality and tech enthusiasts.", price: "22$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmZ7cWfJFldg2VFPpX6XjMdBmr2HJXVyE_Gg&s" },
    { id: 7, name: "Vintage Brown", description: "Classic brown leather", longDescription: "Combining vintage aesthetics with modern reliability, this watch features a rich brown leather strap and a classic dial, making it a perfect choice for timeless style lovers.", price: "32$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9PdEIqInz45BU4EPwGw9g4_8kQxVlHD6eAw&s" },
    { id: 8, name: "Steel Edge", description: "Sharp stainless steel look", longDescription: "A bold stainless steel design with sharp edges and a strong presence. This watch emphasizes durability and a modern industrial aesthetic.", price: "40$", imgUrl: "https://m.media-amazon.com/images/I/61QeNWSSHaL._AC_SL1001_.jpg" },
    { id: 9, name: "Carbon Fit", description: "Lightweight carbon body", longDescription: "Designed with a lightweight carbon body, this watch ensures maximum comfort without compromising strength. Ideal for long wear and active lifestyles.", price: "38$", imgUrl: "https://timex.ph/cdn/shop/files/TW2Y24700.jpg?v=1758511205&width=1080" },
    { id: 10, name: "Golden Hour", description: "Premium gold finish", longDescription: "A premium watch with a golden finish that reflects luxury and elegance. Perfect for special occasions and those who want to stand out.", price: "50$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sK7XkmJoc3zUm39p3bEOFhN1tckCkYcs3Q&s" },
    { id: 11, name: "Explorer", description: "Built for adventure", longDescription: "Crafted for explorers, this watch is built to withstand tough environments. It offers reliability, durability, and a design that suits outdoor adventures.", price: "42$", imgUrl: "https://cdn.shopify.com/s/files/1/0278/9723/3501/files/Breguet-Type-XX-2.jpg?v=1686159523" },
    { id: 12, name: "Urban Grey", description: "Modern city style", longDescription: "A sleek and modern design tailored for urban lifestyles. The Urban Grey blends simplicity with contemporary aesthetics for everyday city wear.", price: "27$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9JLTLq5V6QFlVmCUROROr5d6ot2If_l7y7w&s" },
    { id: 13, name: "Night Rider", description: "Dark theme with glow", longDescription: "Designed for night-time visibility, this watch features subtle glow elements and a dark theme. A perfect companion for evening outings.", price: "36$", imgUrl: "https://m.media-amazon.com/images/I/61srikhJ1IL._AC_SL400_.jpg" },
    { id: 14, name: "Crystal Shine", description: "Glossy polished look", longDescription: "A highly polished watch with a glossy finish that catches light beautifully. Ideal for those who prefer a refined and eye-catching accessory.", price: "48$", imgUrl: "https://res.garmin.com/subcategory/68178/wearables-Instinct-3.png" },
    { id: 15, name: "Eco Time", description: "Energy-efficient design", longDescription: "An environmentally conscious watch designed for efficiency and sustainability. Combines modern style with eco-friendly features.", price: "29$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsS1jCEDXEk-eh119UP-66zeysKqfaFhPp1Q&s" },
    { id: 16, name: "Smart Lite", description: "Light smart features", longDescription: "A lightweight smart watch offering essential features without complexity. Perfect for users who want smart functionality in a simple form.", price: "33$", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsnMrxXcWQ9qZX-166iSr42NWqfIoJbZJ56A&s" },
    { id: 17, name: "Bold Red", description: "Eye-catching red accents", longDescription: "A vibrant watch with bold red accents designed to stand out. Great for adding a pop of color to your outfit.", price: "26$", imgUrl: "https://preview.redd.it/looking-for-affordable-full-white-watches-for-men-v0-s5mu6yjdz01d1.png?auto=webp&s=3b316812529f8bf5121b2e0146bcfdeba6e69bef" },
    { id: 18, name: "Arctic White", description: "Clean white aesthetic", longDescription: "A clean and minimal white design that emphasizes simplicity and elegance. Perfect for a fresh and modern look.", price: "31$", imgUrl: "https://i.etsystatic.com/19429186/r/il/ee0192/7175677984/il_570xN.7175677984_2bpn.jpg" },
    { id: 19, name: "Titan Pro", description: "Strong titanium body", longDescription: "Built with a strong titanium body, this watch offers exceptional durability and a premium feel. Designed for long-term reliability.", price: "55$", imgUrl: "https://i5.walmartimages.com/seo/Weicam-Unisex-Cool-Watches-Roman-Numerals-Creative-Magnetic-Levitation-Balls-Dial-Waterproof-Quartz-Wrist-Watches-Couple-Watch_e62d3912-5e13-4bcd-8bc6-0a5165ba2a90.52d2e68f5dc1636bd2ca52c386002bf6.jpeg" },
    { id: 20, name: "Neo Classic", description: "Blend of modern & classic", longDescription: "A perfect fusion of modern design and classic elements. The Neo Classic is versatile, stylish, and suitable for any occasion.", price: "37$", imgUrl: "https://cdn.strapsco.com/wp-content/uploads/2024/09/most_unique_watches_hamilton_ventura_edge_dune_limited_edition.jpg" }
  ];
}
